# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
zh:
 languageCode: zh-Hans
 contentDir: content/zh
 title: 控制与决策实验室
 params:
    description: Site description in Chinese...
 menu:
   main:
      - name: 主页
        url: home
        weight: 1
      - name: 新闻
        url: post
        weight: 2
      - name: 实验室成员
        url: people
        weight: 3
      - name: 活动
        url: event
        weight: 4
      - name: 论文著作
        url: publication
        weight: 5
      - name: 招生信息
        url: admission
        weight: 55
      - name: 与我们联系
        url: contact
        weight: 6
